name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necesario para el versionado semántico basado en commits

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      id: stepVersion
      with:
        major_pattern: "(MAJOR)"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-${increment}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKERHUB_REPO }}:${{ steps.stepVersion.outputs.version }}
          ${{ vars.DOCKERHUB_REPO }}:latest
        platforms: |
          linux/amd64
          linux/arm64
        cache-from: type=gha # Opcional: Usa la caché de GitHub Actions para builds más rápidos
        cache-to: type=gha,mode=max # Opcional: Guarda la caché para futuros builds

        
