name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login docker
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD

    - name: Build docker image
      run: docker image -t $DOCKERHUB_REPO:0.0.2 .

    - name: Push docker image
      run: docker push $DOCKERHUB_REPO:0.0.2
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
